# Generated by Django 6.0.2 on 2026-02-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("deptId", models.AutoField(primary_key=True, serialize=False)),
                ("departmentName", models.CharField(max_length=100)),
                ("departmentCode", models.CharField(max_length=10, unique=True)),
                ("isActive", models.BooleanField(default=True)),
                ("createdDate", models.DateField(auto_now_add=True)),
                (
                    "departmentType",
                    models.CharField(
                        choices=[
                            ("TECH", "Technology"),
                            ("HR", "Human Resource"),
                            ("FIN", "Finance"),
                            ("MRT", "Marketing"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
