# Generated by Django 6.0.2 on 2026-02-17 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emsbackendapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="department",
            table="faith_Department",
        ),
    ]
