# Generated by Django 6.0.2 on 2026-02-18 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emsbackendapp", "0002_alter_department_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employeeId", models.AutoField(primary_key=True, serialize=False)),
                ("employeeName", models.CharField(max_length=100)),
                ("dateOfJoining", models.DateField()),
                ("contact", models.CharField(max_length=10)),
                (
                    "profileImage",
                    models.ImageField(
                        blank=True, null=True, upload_to="employee-profile/"
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emsbackendapp.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Employees",
            },
        ),
    ]
