# Generated by Django 6.0.2 on 2026-02-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emsbackendapp", "0003_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("certificateId", models.AutoField(primary_key=True, serialize=False)),
                ("certificateName", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Certificates",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="certificate",
            field=models.ManyToManyField(blank=True, to="emsbackendapp.certificate"),
        ),
    ]
