# Generated by Django 6.0.2 on 2026-02-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emsbackendapp", "0004_certificate_employee_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="certificate",
            field=models.ManyToManyField(
                blank=True, null=True, to="emsbackendapp.certificate"
            ),
        ),
    ]
