# Generated by Django 6.0.2 on 2026-02-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emsbackendapp", "0005_alter_employee_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="certificate",
            field=models.ManyToManyField(blank=True, to="emsbackendapp.certificate"),
        ),
    ]
